# Generated by Django 4.2.7 on 2023-12-12 14:51

import books.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('bio', models.TextField()),
                ('picture', models.ImageField(default='default_author_pic.png', upload_to='book/author')),
                ('book_count', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=300)),
                ('set_name', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('audio_file', models.FileField(blank=True, default='', null=True, upload_to=books.models.Books.audio_file_upload_to)),
                ('read_file', models.FileField(blank=True, default='', null=True, upload_to=books.models.Books.read_file_upload_to)),
                ('cost_status', models.CharField(choices=[('P', 'Payment'), ('F', 'Free')], default='F', max_length=1)),
                ('year', models.IntegerField()),
                ('publisher', models.CharField(max_length=200)),
                ('cover_picture', models.ImageField(default='default_book_pic.png', upload_to=books.models.Books.cover_picture_upload_to)),
                ('read_count', models.IntegerField(default=0)),
                ('form_count', models.PositiveIntegerField(default=0, null=True)),
                ('stars_sum', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_audio', models.BooleanField(default=False)),
                ('is_file', models.BooleanField(default=False)),
                ('age_limit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='books.agelimit')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('form_count', models.PositiveIntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SetNameId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='SubGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_genres', models.CharField(max_length=20)),
                ('form_count', models.PositiveIntegerField(default=0, null=True)),
                ('gener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genres')),
            ],
            options={
                'verbose_name': 'SubGenre',
                'verbose_name_plural': 'SubGenres',
            },
        ),
        migrations.CreateModel(
            name='ReadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_file', models.FileField(upload_to=books.models.ReadFile.book_set_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['file', 'pdf', 'epub', 'doc', 'docx'])])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_files', to='books.books')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_link', models.CharField(choices=[('B', 'Buy'), ('R', 'Read'), ('L', 'Listen')], max_length=1)),
                ('link_name', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genres'),
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.language'),
        ),
        migrations.AddField(
            model_name='books',
            name='sub_genere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.subgenres'),
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=books.models.AudioFile.book_set_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['audio', 'mp3', 'MP3'])])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='books.books')),
            ],
        ),
    ]
